delete from Contact;
delete from User;
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));
insert into Contact (firstname, lastname, id) values ('Mickey', 'Mouse', nextval('hibernate_sequence'));